#kivy 1.11.1
Screen:
    id: scr_manager

    MDBoxLayout:
        orientation: "vertical"
        pos_hint: {'center_x': .5, 'center_y': .5}
        size_hint: 1, .3
        MDLabel:
            id: label
            text: 'Hello, World'
            halign: 'center'
            font_style: 'H4'
        MDRaisedButton:
            id: btn
            text: 'Click me'
            pos_hint: {'center_x': .5, 'center_y': .5}
            on_release: app.hello_world()
    